name: invalidate_npm_cache
description: Invalidate the Master NPM cache
runs:
  using: composite
  steps:
  - name: save_cache
    uses: actions/cache/save@v3
    with:
      path: ./modules
      key: v1-deps-{{ checksum "Gemfile" }}
