name: publish_to_pages_production
description: Publish to cloudflare pages (production)
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account id'
    required: true
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare token'
    required: true
runs:
  using: composite
  steps:
  - name: Publish to cloudflare pages (production)
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
    run: |
      cd _site
      npx wrangler pages publish . --project-name=websockets-pages --branch=main
      echo "New website - http://cf-pages-websockets.binary.com"
    shell: bash
