name: bundle_install
description: Bundle Install
runs:
  using: composite
  steps:
  - restore_cache:
    name: Bundle modules cache restore
    keys:
      - bundle-v1-{{ checksum "Gemfile" }}
      - bundle-v1-
  - bundle_install:
    name: Bundle install
    run: |
          bundle install --path ./modules
  - save_cache:
    name: Bundle modules cache save
    key: bundle-v1-{{ checksum "Gemfile" }}
    with:
      paths:
        - "modules"
