name: bundle_install
description: Bundle Install
runs:
  using: composite
  steps:
  - name: Bundle modules cache restore
    id: cache-modules
    uses: actions/cache/restore@v3
    with: 
      path: ./modules
      key: bundle-v1-{{ checksum "Gemfile" }}

  - name: Bundle install
    if: steps.cache-modules.outputs.cache-hit != 'true'
    shell: bash
    run: bundle install --path ./modules

