name: versioning
description: Versioning
inputs:
  RELEASE_TYPE:
    description: Release Type
    required: false

runs:
  using: composite
  steps:
    - name: Tag build
      run: echo "${GITHUB_REF#refs/heads/} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > _site/version
      shell: bash
