name: send_slack_notifications
description: Send Slack notifications
inputs:
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook URL'
    required: true
  status:
    description: 'Job status'
    required: true
  RELEASE_TYPE:
    description: 'Release type'
    required: true
  version:
    description: 'Version'
    required: true
    default: 'N/A'
runs:
  using: composite
  steps:
  - name: Send Slack Notification on Success

    if: inputs.status == 'success'
    run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{
        "text": "${{ inputs.RELEASE_TYPE }} Release succeeded for dsmarttrader.deriv.com with version ${{ inputs.VERSION }}"
        }' \
          ${{ inputs.SLACK_WEBHOOK_URL }}
    shell: bash

  - name: Send Slack Notification on Failure
    if: inputs.status == 'failure'
    run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "${{ inputs.RELEASE_TYPE }} Release failed for dsmarttrader.deriv.com with version ${{ inputs.VERSION }}"
          }' \
          ${{ inputs.SLACK_WEBHOOK_URL }}
    shell: bash
