name: Websocket Production Workflow
on:
  push:
    branches:
      - master
jobs:
  build_test_and_publish:
    name: Build, Test and Publish to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Bundle Install
        uses: ./.github/actions/bundle_install
      - name: Build Jekyll site
        uses: ./.github/actions/build_jekyll_site
      - name: invalidate master cache
        uses: ./.github/actions/invalidate_master_cache
      - name: Versioning
        uses: ./.github/actions/versioning
        with:
          release_type: production
      - name: Publish to Cloudflare Pages Production
        uses: "./.github/actions/publish_to_pages_production"
        with:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Build Docker image and push to Docker hub and K8S
        uses: "./.github/actions/build_and_push_docker_image"
        with:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_ORGANISATION: ${{ secrets.DOCKERHUB_ORGANISATION }}
          K8S_NAMESPACE: "developers-binary-com-production"
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          SERVICEACCOUNT_TOKEN: ${{ secrets.SERVICEACCOUNT_TOKEN }}
          CA_CRT: ${{ secrets.CA_CRT }}
          APP_VERSION: latest
      

  send_slack_notification:
    name: Send Slack notification
    runs-on: ubuntu-latest
    if: always()
    needs: [build_test_and_publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v3
      - name: Send Slack Notification
        uses: "./.github/actions/send_slack_notifications"
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
          release_type: Production
          version: $GITHUB_REF_NAME
